modLoader = "javafml" #mandatory
loaderVersion = "[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"
[[mods]] #mandatory
modId = "tr18sgi" #mandatory
version = "1.0.0" #mandatory
displayName = "Gregified Integrations" #mandatory
authors = "The Realm 18 Studios" #optional

description = ''''''
[[dependencies.tr18sgi]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
[[dependencies.tr18sgi]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.tr18sgi]]
modId = "gtceu"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"
